fix wrong signal being sent
FortnoxAB/config-reloader pull request #5
Opened 2023-10-03 10:52 UTC by xonvanetta

2023-10-03 11:01 UTC, xonvanetta commented
Hmm, this works as expected, I think there is something wrong with how it doesn't find the path from the event, that's why it defaults to the last signal sent

2023-10-06 14:21 UTC, curantes approved these changes
LGTM

2023-10-06 14:33 UTC, jonaz requested changes

2023-10-06 14:33 UTC, jonaz commented on Makefile
> +push: docker
remove

2023-10-06 14:35 UTC, jonaz approved these changes

2023-10-06 14:35 UTC, merged